---
- hosts: workstation

  tasks:
    - name: install Alfred
      mac_pkg: pkg_type=app
               url=https://github.com/maarten/ansible-osx.git
               archive_type=zip archive_path='Alfred 2.app'
      sudo: yes

