---
- hosts: workstation

  tasks:
    - name: install Charles Proxy
      mac_pkg: pkg_type=app
               url=http://www.charlesproxy.com/assets/release/3.8.3/charles-proxy-3.8.3a-applejava.dmg
               archive_type=dmg archive_path=Charles.app
      sudo: yes
