---
- hosts: workstation

  tasks:
    - name: install iterm2
      mac_pkg: pkg_type=app
               url=http://www.iterm2.com/downloads/stable/iTerm2_v1_0_0.zip
               archive_type=zip archive_path=iTerm.app
      sudo: yes

