---
- hosts: workstation

  tasks:
    - name: install macports
      mac_pkg: pkg_name=org.macports.MacPorts pkg_version=1.0
               url=https://distfiles.macports.org/MacPorts/MacPorts-2.2.1-10.9-Mavericks.pkg
      sudo: yes
