---
- hosts: workstation

  tasks:
    - name: Download Spotify
      mac_pkg: pkg_type=app
               url=http://download.spotify.com/SpotifyInstaller.zip
               archive_type=zip archive_path='SpotifyInstaller.app'
      sudo: yes

    - name: Install Spotify
      command: open /Applications/SpotifyInstaller.app
