---
- hosts: workstation

  tasks:
    - name: install vagrant
      mac_pkg: pkg_name=com.vagrant.vagrant pkg_version=1.4.4
               url=https://dl.bintray.com/mitchellh/vagrant/Vagrant-1.4.3.dmg
               archive_type=dmg archive_path=Vagrant.pkg
      sudo: yes

